apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-aws-eks-deployment
  labels:
    app: spring-aws-eks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-aws-eks
  template:
    metadata:
      labels:
        app: spring-aws-eks
    spec:
      containers:
        - name: spring-aws-eks
          image: <<REPLACE WITH DOCKER IMAGE>>>
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: spring-aws-eks-config